### ISSUE TITLE
local variable 'B_hat' referenced before assignment when dataframe contains NaN

### ISSUE THREAD

**Issue by such3r** [epigenelabs/pyComBat#10]
Code:
>	df = pd.DataFrame(np.random.rand(10, 9))
>	df.iloc[5, 5] = np.nan
>	batches = [0]*3+[1]*3+[2]*3
>	dft_ = pycombat(df, batches)

Causes:
>   dft_ = pycombat(df, batches)
>  File ".../miniconda3/lib/python3.8/site-packages/combat/pycombat.py", line 661, in pycombat
>    B_hat, grand_mean, var_pooled = calculate_mean_var(
>  File ".../miniconda3/lib/python3.8/site-packages/combat/pycombat.py", line 458, in calculate_mean_var
>    [i / n_array for i in n_batches]), B_hat[0:n_batch])
>UnboundLocalError: local variable 'B_hat' referenced before assignment

**Comment by abdelkaderbehdenna** [comment]
Hi @such3r,

Thanks for reaching out to us! This issue is related to the presence of NaNs in your dataset, pyComBat failing in the creation of the B_hat object. We added a feature to warn the users about this problem before trying to create B_hat, with an exception being raised if NaNs are detected in the data.
