### ISSUE TITLE
pycombat for bulk RNAseq dataset?

### ISSUE THREAD

**Issue by hhageBA** [epigenelabs/pyComBat#35]
Hi, from what I understood,  pyCombat have been developped and tested on microarray gene expression data, can we use it also for RNA gene expression data ? Thanks!

**Comment by EpigeneMax** [comment]
Hi @hhageBA, great question!

It turns out that microarray and RNA-Seq data do not follow the same statistical distributions. While you can run pyCombat on RNA-Seq data, the validity of the output is questionable.

Fortunately, the model of ComBat can be adjusted to use distributions more suitable for RNA-Seq data (see [this paper](https://doi.org/10.1093/nargab/lqaa078)). A ComBat-Seq tool exists in the [R sva package](https://bioconductor.org/packages/release/bioc/html/sva.html), and **we have ported it to Python**.
Check out our [InMoose repository](https://github.com/epigenelabs/inmoose) to access both pyCombat and pyCombat-Seq!
